version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pitchflow-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password_secure_123
      POSTGRES_DB: pitchflow
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pitchflow-backend
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres_password_secure_123@db:5432/pitchflow
      - JWT_SECRET=super_secret_pitchflow_key_123456_production_ready
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - ADMIN_EMAIL=admin@pitchflow.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      - db
    networks:
      - default
      - portfolio_default


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=https://pitchflow.riturajshukla.tech
    container_name: pitchflow-frontend
    restart: always
    ports:
      - "127.0.0.1:3000:80"

    depends_on:
      - backend
    networks:
      - default
      - portfolio_default

volumes:
  pgdata:

networks:
  portfolio_default:
    external: true
  default:

